CREATE TABLE IF NOT EXISTS `integration_connector` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '连接器主键',
  `name` varchar(128) NOT NULL COMMENT '连接器名称',
  `alias` varchar(128) DEFAULT NULL COMMENT '连接器别名',
  `base_url` varchar(1024) NOT NULL COMMENT '外部 API 基础地址',
  `auth_type` varchar(64) NOT NULL DEFAULT 'NONE' COMMENT '认证类型：NONE/API_KEY/OAUTH2_CLIENT_CREDENTIALS',
  `auth_config_json` longtext COMMENT '认证配置 JSON',
  `connect_params_json` longtext COMMENT '连接参数 JSON',
  `owner_user_id` bigint DEFAULT NULL COMMENT '创建人用户ID（历史数据可为空）',
  `permission_scope` tinyint DEFAULT NULL COMMENT '权限范围：1仅创建人可见可操作，2所有人可见仅创建人可操作，3所有人可见可操作（历史数据可为空，由代码兼容）',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/ACTIVE/DISABLED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_connector_name` (`name`),
  KEY `idx_integration_connector_owner_user` (`owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='自定义外部 API 连接器';

CREATE TABLE IF NOT EXISTS `integration_connector_api` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '连接器 API 主键',
  `connector_id` bigint NOT NULL COMMENT '所属连接器ID',
  `connect_id` varchar(128) DEFAULT NULL COMMENT '绑定的鉴权ID',
  `connect_name` varchar(255) DEFAULT NULL COMMENT '绑定的鉴权名称',
  `api_code` varchar(128) NOT NULL COMMENT 'API 编码',
  `api_name` varchar(255) NOT NULL COMMENT 'API 名称',
  `description` text COMMENT 'API 描述',
  `method` varchar(16) NOT NULL DEFAULT 'POST' COMMENT 'HTTP 方法',
  `path_template` varchar(1024) NOT NULL COMMENT '路径模板',
  `headers_json` longtext COMMENT 'Header 模板 JSON',
  `query_params_json` longtext COMMENT 'Query 模板 JSON',
  `body_template_json` longtext COMMENT 'Body 模板 JSON',
  `content_type` varchar(128) DEFAULT NULL COMMENT '请求内容类型',
  `input_schema_json` longtext COMMENT '工具输入 Schema JSON',
  `output_mapping_json` longtext COMMENT '输出映射 JSON',
  `identity_binding_policy_json` longtext COMMENT '身份注入策略 JSON',
  `tool_name` varchar(255) DEFAULT NULL COMMENT '发布后的工具名称',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用：1启用，0停用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_connector_api_connector_code` (`connector_id`,`api_code`),
  UNIQUE KEY `uk_integration_connector_api_tool_name` (`tool_name`),
  KEY `idx_integration_connector_api_connector` (`connector_id`,`id`),
  KEY `idx_integration_connector_api_enabled` (`enabled`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='自定义外部 API 目录';
