CREATE TABLE IF NOT EXISTS `runtime_approval` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审批主键',
  `approval_code` char(26) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '审批编码(ULID)',
  `run_id` bigint NOT NULL COMMENT '关联执行ID',
  `run_code` char(26) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '执行编码',
  `session_id` bigint DEFAULT NULL COMMENT '关联会话ID',
  `assistant_message_id` bigint DEFAULT NULL COMMENT 'assistant消息ID',
  `tool_call_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '模型工具调用ID',
  `tool_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '工具名称',
  `tool_display_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工具展示名',
  `tool_arguments_json` json NOT NULL COMMENT '工具调用参数',
  `tool_result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '审批后工具执行结果',
  `approval_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'PENDING/APPROVED/REJECTED/CANCELLED',
  `execution_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'NOT_STARTED/RUNNING/SUCCEEDED/FAILED/SKIPPED',
  `risk_level` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'LOW/MEDIUM/HIGH',
  `trigger_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '触发审批原因',
  `analysis_json` json DEFAULT NULL COMMENT '风险分析结果',
  `requested_by` bigint DEFAULT NULL COMMENT '发起用户ID',
  `decided_by` bigint DEFAULT NULL COMMENT '审批用户ID',
  `decision_comment` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审批备注',
  `decided_at` datetime DEFAULT NULL COMMENT '审批时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_runtime_approval_code` (`approval_code`),
  KEY `idx_runtime_approval_run` (`run_id`,`id`),
  KEY `idx_runtime_approval_run_code` (`run_code`,`id`),
  KEY `idx_runtime_approval_status` (`approval_status`,`updated_at`,`id`),
  KEY `idx_runtime_approval_tool` (`tool_name`,`approval_status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='运行时工具人工审批表';
