CREATE TABLE IF NOT EXISTS `runtime_file_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_code` char(26) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '文件编码（ULID）',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `session_id` bigint DEFAULT NULL COMMENT '会话ID',
  `session_code` char(26) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '会话编码',
  `origin_message_id` bigint DEFAULT NULL COMMENT '来源消息ID',
  `origin_event_id` bigint DEFAULT NULL COMMENT '来源事件ID',
  `parent_file_code` char(26) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '父文件编码',
  `file_role` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '文件角色 UPLOAD/TEMP/ARTIFACT',
  `producer_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '产生方式 USER_UPLOAD/WRITE_ARTIFACT/SYSTEM',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '状态 ACTIVE/DELETED/EXPIRED/FAILED',
  `display_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '展示文件名',
  `storage_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '存储文件名',
  `extension` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '扩展名',
  `content_type` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'MIME类型',
  `size_bytes` bigint DEFAULT NULL COMMENT '文件大小（字节）',
  `sha256` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '内容SHA-256',
  `logical_root` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '逻辑根目录 UPLOADS/OUTPUTS/TEMP/PROFILE',
  `logical_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '逻辑相对路径',
  `virtual_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '虚拟路径',
  `local_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '本地真实路径',
  `local_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PRESENT' COMMENT '本地副本状态 PRESENT/MISSING/DELETED/FAILED',
  `bucket` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'MinIO bucket',
  `object_name` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'MinIO object key',
  `minio_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PENDING' COMMENT 'MinIO状态 PENDING/UPLOADED/MISSING/FAILED',
  `metadata_json` json DEFAULT NULL COMMENT '扩展元数据JSON',
  `expired_at` datetime DEFAULT NULL COMMENT '过期时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '软删除时间',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_runtime_file_asset_code` (`file_code`),
  KEY `idx_runtime_file_asset_user_session` (`user_id`,`session_id`,`id`),
  KEY `idx_runtime_file_asset_origin_message` (`origin_message_id`,`id`),
  KEY `idx_runtime_file_asset_origin_event` (`origin_event_id`,`id`),
  KEY `idx_runtime_file_asset_role_status` (`file_role`,`status`,`id`),
  KEY `idx_runtime_file_asset_parent` (`parent_file_code`),
  KEY `idx_runtime_file_asset_virtual_path` (`user_id`,`session_id`,`virtual_path`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='运行时文件资产表';
