import { ROUTE_PATHS } from '@/router/routePaths';

export const FRONT_HOME_VIEWS = Object.freeze({
    CHAT: 'chat',
    FILES: 'files',
    SKILLS: 'skills',
    EXPERT_PACKAGES: 'expert-packages',
    INTELLIGENT_CHAT: 'intelligent-chat',
    DATASET_CHAT: 'dataset-chat',
    RESOURCES: 'resources',
});

export const FRONT_SIDEBAR_ITEMS = Object.freeze([
    {
        id: FRONT_HOME_VIEWS.CHAT,
        label: 'AI 助手对话',
        shortLabel: '对话',
        icon: 'chat_bubble',
        view: FRONT_HOME_VIEWS.CHAT,
        path: ROUTE_PATHS.frontChat,
        pageTitle: 'AI 助手对话',
        pageDescription: '多轮上下文对话与任务协作',
        showPageHeader: false,
    },
    {
        id: FRONT_HOME_VIEWS.FILES,
        label: '文件与记忆',
        shortLabel: '文件',
        icon: 'folder_managed',
        view: FRONT_HOME_VIEWS.FILES,
        path: ROUTE_PATHS.frontFiles,
        pageTitle: '文件与记忆',
        pageDescription: '统一管理文件资产与个人记忆',
        showPageHeader: true,
    },
    {
        id: FRONT_HOME_VIEWS.SKILLS,
        label: '技能市场',
        shortLabel: '技能',
        icon: 'widgets',
        view: FRONT_HOME_VIEWS.SKILLS,
        path: ROUTE_PATHS.frontSkills,
        pageTitle: '技能市场',
        pageDescription: '按业务能力发现并进入技能对话',
        showPageHeader: true,
    },
    {
        id: FRONT_HOME_VIEWS.EXPERT_PACKAGES,
        label: '专家技能包',
        shortLabel: '专家',
        icon: 'psychology',
        view: FRONT_HOME_VIEWS.EXPERT_PACKAGES,
        path: ROUTE_PATHS.frontExpertPackages,
        pageTitle: '专家技能包',
        pageDescription: '选择固定技能与工具组合进入专业对话',
        showPageHeader: false,
    },
    {
        id: FRONT_HOME_VIEWS.INTELLIGENT_CHAT,
        label: 'AI 问答',
        shortLabel: 'AI问答',
        icon: 'help',
        view: FRONT_HOME_VIEWS.INTELLIGENT_CHAT,
        path: ROUTE_PATHS.frontIntelligentChat,
        pageTitle: 'AI 问答',
        pageDescription: '基于知识库进行可溯源问答',
        showPageHeader: false,
    },
    {
        id: FRONT_HOME_VIEWS.DATASET_CHAT,
        label: 'AI 问数',
        shortLabel: 'AI问数',
        icon: 'database',
        view: FRONT_HOME_VIEWS.DATASET_CHAT,
        path: ROUTE_PATHS.frontDatasetChat,
        pageTitle: 'AI 问数',
        pageDescription: '基于数据集执行只读分析与统计',
        showPageHeader: false,
    },
    {
        id: FRONT_HOME_VIEWS.RESOURCES,
        label: '资源总览',
        shortLabel: '资源',
        icon: 'inventory_2',
        view: FRONT_HOME_VIEWS.RESOURCES,
        path: ROUTE_PATHS.frontResources,
        pageTitle: '资源总览',
        pageDescription: '查看当前角色下已授权和未授权的技能与工具',
        showPageHeader: true,
    },
]);

export function getFrontSidebarItemByView(view) {
    return FRONT_SIDEBAR_ITEMS.find(item => item.view === view) || null;
}
